# Default values for PHP.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
image:
  repository: 10.43.195.153:5000/hchan-ias/hack19-catchet
  tag: 0.0.9
  pullPolicy: IfNotPresent

# define environment variables here as a map of key: value
env:

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: hack19-catchet
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
env:
   DBDRIVER: pgsql
   DB_HOST: catchet-db
   DB_PORT: 5432
   DB_DATABASE: postgres
   DB_USERNAME: postgres
   DB_PASSWORD: postgres
   DB_PREFIX: chq_
   APP_KEY: "${APP_KEY:-null}"
   APP_LOG: errorlog
   DEBUG: false

catchet-db:
  postgresqlUsername: postgres
  postgresqlPassword: postgres
  persistence:
    enabled: true
    mountPath: /var/lib/postgresql/data
